# docs/src/orchid/resources/config.yml
site:
  about:
    siteName: ç®—æ³•(ç¬¬å››ç‰ˆ)kotlinä¸ªäººå®ç°
    siteDescription: ğŸ“•ç®—æ³•(ç¬¬å››ç‰ˆ)kotlinä¸ªäººå®ç°/éƒ¨åˆ†è¯¾åä¹ é¢˜/éƒ¨åˆ†æé«˜é¢˜
Editorial:
  primaryColor: '#DE9149'
  social:
    github: 'xmmmmmovo/Algorithms4thEditionKotlinSolutions'
  metaComponents: # this is the replacement for the deprecated automatic search addition
    - type: 'orchidSearch'
  menu:
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
    - type: 'page'
      itemId: 'Changelog'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'
kotlindoc:
  sourceDirs:
    - './../../../../src/main/kotlin'
  sourcePages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'kotlindoc'
        itemTitleType: 'SIGNATURE'
        includeItems: true